import os

# game settings
RES=WIDTH, HEIGHT=1600, 900
FPS=60
SCROLL_SPEED=8 # speed of the bird
ROOT_DIR=os.path.join(os.path.dirname(os.path.dirname(__file__)))
GRAVITY = 1

# bird settings
BIRD_POS=WIDTH//4, HEIGHT//3
BIRD_SCALE=1.5
BIRD_ANIMATION_TIME=150
BIRD_JUMP_VALUE=-16
BIRD_JUMP_ANGLE=25 # degree

# ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# pipe settings
PIPE_WIDTH=250
PIPE_HEIGHT=HEIGHT
DIST_BETWEEN_PIPES=650
GAP_HEIGHT=320
HALF_GAP_HEIGHT=GAP_HEIGHT//2

# fire
WIN_SIZE = WIDTH, HEIGHT = RES
STEPS_BETWEEN_COLORS = 4
COLORS = ['black', 'red', 'orange', 'yellow', 'white']
PIXEL_SIZE = 4

FIRE_REPS = 4
FIRE_WIDTH = WIDTH // (PIXEL_SIZE * FIRE_REPS)
FIRE_HEIGHT = HEIGHT // PIXEL_SIZE
